### ISSUE TITLE
Support _ thousands separator; handle exponent floating point notation

### ISSUE THREAD

**Issue by ccoVeille** [grol-io/grol#103]
Go, JavaScript, and other languages support the following notation

1_000_000 for 1e6

BTW, is 1e6 supported?

**Comment by ldemailly** [comment]
1.23e6 isn't yet supported no, probably need to add that before _

in theory supporting finance style numbers would be more useful eg

23,000.43

but that would break function calls (param lists) and is US style (french would be 23.000,43 if I recall)

**Comment by ldemailly** [comment]
btw is _ actually only for thousands or just simply ignored in middle of numbers?

eg 1_23__4.5 is valid 1234.5 ?

**Comment by ccoVeille** [comment]
> 1.23e6 isn't yet supported no, probably need to add that before _
> 
> in theory supporting finance style numbers would be more useful eg
> 
> 23,000.43
> 
> but that would break function calls (param lists) and is US style (french would be 23.000,43 if I recall)

French is 23 000,43

**Comment by ccoVeille** [comment]
> btw is _ actually only for thousands or just simply ignored in middle of numbers?
> 
> eg 1_23__4.5 is valid 1234.5 ?

It's valid 😬

https://go.dev/ref/spec#Integer_literals

**Comment by ldemailly** [comment]
easy enough then to just ignore all _ in the middle of numbers

now for exponent notation I can either reinvent the wheel or call go's parse float, though... having minimal impl sounds good
