### ISSUE TITLE
fix tag regex here and discord bot

### ISSUE THREAD

**Issue by ldemailly** [grol-io/grol#50]
thank I fixed that bug in fortio/workflows but when I copied pre workflow files from multicurl I forgot about, nice catch

_Originally posted by @ldemailly in https://github.com/grol-io/grol-discord-bot/pull/16#discussion_r1685219794_

**Comment by ldemailly** [comment]
see also $ issue in https://github.com/grol-io/grol-discord-bot/pull/16

**Comment by ldemailly** [comment]
@ccoVeille moving the discussion here, so somehow

https://github.com/fortio/workflows/blob/main/.github/workflows/releaser.yml#L19-L23

works

as in I did these tags

v0.1.0-pre7
v0.1.0-test1
v0.1.0-test2

and only pre7 was built https://github.com/fortio/workflows/actions/workflows/releaser.yml

now weird indeed that the   https://github.com/grol-io/grol/blob/main/.github/workflows/releaser.yml#L5-L8

did build

https://github.com/grol-io/grol/actions/workflows/releaser.yml

**Comment by ldemailly** [comment]
and https://github.com/grol-io/grol/actions/workflows/releaser.yml isn't building v0.22.0-test1

very strange

**Comment by ccoVeille** [comment]
Strange indeed.

As long as you managed to make something that "works", not necessarily as it should

**Comment by ldemailly** [comment]
I am confused because some hours after a -test release showed up... oh well
